ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS callback_url TEXT NULL;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS callback_mode TEXT NOT NULL DEFAULT 'none';

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS callback_status TEXT NULL;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS callback_error TEXT NULL;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS callback_sent_at TIMESTAMPTZ NULL;
